// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: fibo.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FiboRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FiboRequest) Reset() {
	*x = FiboRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fibo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FiboRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiboRequest) ProtoMessage() {}

func (x *FiboRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fibo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiboRequest.ProtoReflect.Descriptor instead.
func (*FiboRequest) Descriptor() ([]byte, []int) {
	return file_fibo_proto_rawDescGZIP(), []int{0}
}

func (x *FiboRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FiboResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FiboResponse) Reset() {
	*x = FiboResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fibo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FiboResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiboResponse) ProtoMessage() {}

func (x *FiboResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fibo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiboResponse.ProtoReflect.Descriptor instead.
func (*FiboResponse) Descriptor() ([]byte, []int) {
	return file_fibo_proto_rawDescGZIP(), []int{1}
}

func (x *FiboResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_fibo_proto protoreflect.FileDescriptor

var file_fibo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x69, 0x62, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0b, 0x46, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0c, 0x46, 0x69, 0x62, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x45, 0x0a, 0x0b, 0x46, 0x69, 0x62, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x36, 0x0a, 0x09, 0x46, 0x69, 0x62, 0x6f, 0x6e, 0x61, 0x63, 0x63, 0x69, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x67, 0x6c, 0x61, 0x73, 0x2d, 0x73, 0x6f,
	0x61, 0x72, 0x65, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2d, 0x71, 0x75, 0x69, 0x63, 0x6b, 0x2f, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_fibo_proto_rawDescOnce sync.Once
	file_fibo_proto_rawDescData = file_fibo_proto_rawDesc
)

func file_fibo_proto_rawDescGZIP() []byte {
	file_fibo_proto_rawDescOnce.Do(func() {
		file_fibo_proto_rawDescData = protoimpl.X.CompressGZIP(file_fibo_proto_rawDescData)
	})
	return file_fibo_proto_rawDescData
}

var file_fibo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fibo_proto_goTypes = []interface{}{
	(*FiboRequest)(nil),  // 0: proto.FiboRequest
	(*FiboResponse)(nil), // 1: proto.FiboResponse
}
var file_fibo_proto_depIdxs = []int32{
	0, // 0: proto.FiboService.Fibonacci:input_type -> proto.FiboRequest
	1, // 1: proto.FiboService.Fibonacci:output_type -> proto.FiboResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fibo_proto_init() }
func file_fibo_proto_init() {
	if File_fibo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fibo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FiboRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fibo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FiboResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fibo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fibo_proto_goTypes,
		DependencyIndexes: file_fibo_proto_depIdxs,
		MessageInfos:      file_fibo_proto_msgTypes,
	}.Build()
	File_fibo_proto = out.File
	file_fibo_proto_rawDesc = nil
	file_fibo_proto_goTypes = nil
	file_fibo_proto_depIdxs = nil
}
